### ISSUE TITLE
Uncaught Invariant Violation

### ISSUE THREAD

**Issue by mikedizon** [ianbjorndilling/react-typewriter#5]
Getting strange error on 0.1.2

Uncaught Invariant Violation: TypeWriter.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.

**Comment by mikedizon** [comment]
Strange, still happening with version 0.2.1

Uncaught Invariant Violation: t.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.

**Comment by frostney** [comment]
This should be fixed in version 0.2.2. Please update.

@mikedizon You were actually correct in assuming that the library needed to enforce its React 0.14 dependency. React 0.14 has a check on `Component.prototype.isReactComponent` which only works if there's a hard dependency on React 0.14. It's kinda weird that this didn't work as expected in my initial tests though.

**Comment by mikedizon** [comment]
Nice!
